language: dart
sudo: required

jobs:
  include:
    - stage: analyze
      name: "SDK: dev; TASKS: `dartanalyzer --fatal-warnings .`"
      dart: "dev"
      env: PKGS="./"
      script: ./tool/travis.sh dartanalyzer
    - stage: analyze
      name: "SDK: 2.2.0; TASKS: `dartanalyzer --fatal-warnings .`"
      dart: "2.2.0"
      env: PKGS="./"
      script: ./tool/travis.sh dartanalyzer

    - stage: test
      name: "SDK: dev; TASKS: `pub run test`"
      dart: dev
      env: PKGS="./"
      script: ./tool/travis.sh test
    - stage: test
      name: "SDK: 2.2.0; TASKS: `pub run test`"
      dart: "2.2.0"
      env: PKGS="./"
      script: ./tool/travis.sh test

stages:
  - analyze
  - test

cache:
  directories:
    - "$HOME/.pub-cache"