language: dart
install:
  - gem install coveralls-lcov

jobs:
  include:
    - stage: analyze_and_test
      name: "SDK: 2.12.0"
      dart: "2.12.0"
      script: make

stages:
  - analyze_and_test

cache:
  directories:
    - "$HOME/.pub-cache"
