name: dart-otp
description: dart-otp is a dart package to generate and verify one-time passwords.
version: 1.0.2
author: Gin <gin.lance.inside@hotmail.com>

homepage: https://github.com/BrunoMiguens/dart-otp

environment:
  sdk: ">=1.13.0 <3.0.0"

dependencies:
  crypto: ^2.0.3
  base32: ^1.0.1
